### ISSUE TITLE
关于文件参数问题

### ISSUE THREAD

**Issue by lxk767363331** [HRNet/HigherHRNet-Human-Pose-Estimation#40]
Parameters shown in document models.py   POSE_HIGHER_RESOLUTION_NET.DECONV.NUM_DCONVS = 2
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/models/pose_higher_hrnet.py#L512    for i in range(self._**num_deconvs**_):****
The value of the parameter num_deconvs should be the value of DECONV.NUM_DECONVS

But the value of the parameter NUM_DECONVS is not found in the parameter file.

I think, perhaps by mistake, the NUM_DECONVS in file models.py   was incorrectly written as NUM_DCONVS.

If this is the case above, please ask why num_deconvs is equal to 2.
If this is not the case, please tell us where this parameter is set for num_deconvs.
I look forward to your answers, thank you.

**Comment by bowenc0221** [comment]
It is under `MODEL.EXTRA`

https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/models/pose_higher_hrnet.py#L256

https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/models/pose_higher_hrnet.py#L305

**Comment by lxk767363331** [comment]
Could you show me where the parameter MODEL.EXTRA.DECONV.NUM_DECONVS&nbsp; set?
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/config/models.py#L52

There are no NUM_DECONVS here, and the reference here is to NUM_DCONVS not NUM_DECONVS, missing a letter E.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bowen Cheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 凌晨5:58
收件人:&nbsp;"HRNet/HigherHRNet-Human-Pose-Estimation"<HigherHRNet-Human-Pose-Estimation@noreply.github.com&gt;;
抄送:&nbsp;"不要冲动保持心态"<767363331@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HRNet/HigherHRNet-Human-Pose-Estimation] 关于文件参数问题 (#40)





 
It is under MODEL.EXTRA
 
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/models/pose_higher_hrnet.py#L256
 
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/models/pose_higher_hrnet.py#L305

**Comment by bowenc0221** [comment]
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/experiments/coco/higher_hrnet/w48_640_adam_lr1e-3.yaml#L92
