### ISSUE TITLE
Why restore resolution through deconv instead of HRNet?

### ISSUE THREAD

**Issue by jialeli1** [HRNet/HigherHRNet-Human-Pose-Estimation#41]
Compared to HRNet, the newly added deconv operation can restore the resolution again. But why not directly use 1/2 resolution in the first stage of HRNet, so that the final 1/2 resolution can be directly restored in the style of HRNet.
Is there any limitation or deficiency? This really confuses me, thank you for your answer.

**Comment by dangnh0611** [comment]
@jialeli1 hi, could you share your thoughts about this ?
refer: https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/issues/19
