### ISSUE TITLE
Can't really understand the parameter in affine transformation

### ISSUE THREAD

**Issue by wwang107** [HRNet/HigherHRNet-Human-Pose-Estimation#53]
First of all, great work! However, I found a hard time to understand what you exactly do in the transformation, could you eleborate step-by-step?

https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/dataset/transforms/transforms.py#L100-L121

**Comment by shield218** [comment]
Hi, Have you figured out yet ? I'm confused how these 3 point pairs are selected to calculate the affine matrix too, it does look weird when you write it down and draw a draft on the paper, these points are neither vertices of the selected recutangular nor other representative points
