### ISSUE TITLE
where is thr crowdposetools

### ISSUE THREAD

**Issue by guanyonglai** [HRNet/HigherHRNet-Human-Pose-Estimation#56]
I ran the code, and it raise an error:
  File "/home/guanyonglai/gyl/goods_project/KP/HigherHRNet-Human-Pose-Estimation/tools/../lib/dataset/CrowdPoseKeypoints.py", line 15, in <module>
    import crowdposetools
ModuleNotFoundError: No module named 'crowdposetools

**Comment by bowenc0221** [comment]
Please follow step 5 in [installation](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation#installation).

**Comment by Ankitjaiswal1201** [comment]
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/pull/65?_pjax=%23repo-content-pjax-container#issuecomment-898467412

Here is how i solved it.
