### ISSUE TITLE
How many GPUs do you used?

### ISSUE THREAD

**Issue by greatlog** [HRNet/HigherHRNet-Human-Pose-Estimation#64]
The default learning rate is 1e-3 for 12 images per GPU. However, I do not know the default number of GPUs, i.e. I cannot know the total batch size. The total learning rate should be promotional with the total batch size. So how should I adjust my learning rate if I use different number of GPUs as you do?

Thanks!

**Comment by noymer** [comment]
>The code is developed and tested using 4 NVIDIA P100 GPU cards. 
>
>https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation#environment
