### ISSUE TITLE
 module 'torch.onnx' has no attribute 'set_training'

### ISSUE THREAD

**Issue by sunmengnan** [HRNet/HigherHRNet-Human-Pose-Estimation#81]
when training using dist_train.py,
whether using multi-gpu or not, all get the error:
 module 'torch.onnx' has no attribute 'set_training'.
Anyone know how to fix it? Thanks

**Comment by qwe1256** [comment]
Hi, sunmengnan,

I have the same issue. Could you share your solution to fix this issue? Thank you. 

qwe1256
