### ISSUE TITLE
Train on windows,GPU don't work.

### ISSUE THREAD

**Issue by happydog555** [HRNet/HigherHRNet-Human-Pose-Estimation#84]
=> init stage4.2.fuse_layers.0.3.0.weight from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.weight from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.weight from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.bias from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.bias from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.running_mean from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.running_mean from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.running_var from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.running_var from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.num_batches_tracked from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.num_batches_tracked from models/pytorch/imagenet/hrnet_w32-36af842e.pth
pytorch version is too old, how about build by yourself?
Traceback (most recent call last):
  File "tools/dist_train.py", line 319, in <module>
    main()
  File "tools/dist_train.py", line 123, in main
    tb_log_dir
  File "tools/dist_train.py", line 227, in main_worker
    torch.cuda.set_device(args.gpu)
  File "C:\Users\cust708\.conda\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 261, in set_device
    device = _get_device_index(device)
  File "C:\Users\cust708\.conda\envs\pytorch\lib\site-packages\torch\cuda\_utils.py", line 25, in _get_device_index
    device = torch.device(device)
RuntimeError: Invalid device string: '0'

**Comment by happydog555** [comment]
(pytorch) D:\UserData\LiMeng\POSE_ROOT>python tools/dist_train.py --cfg experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml
=> creating output\coco_kpt\pose_higher_hrnet\w32_512_adam_lr1e-3
=> creating log\coco_kpt\pose_higher_hrnet\w32_512_adam_lr1e-3_2021-03-03-10-30
Namespace(cfg='experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml', dist_url='tcp://127.0.0.1:23456', gpu=None, opts=[], rank=0, world_size=1)
AUTO_RESUME: True
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  BASE_SIGMA: 2.0
  BASE_SIZE: 256.0
  DATASET: coco_kpt
  DATASET_TEST: coco
  DATA_FORMAT: jpg
  FLIP: 0.5
  INPUT_SIZE: 512
  INT_SIGMA: False
  MAX_NUM_PEOPLE: 30
  MAX_ROTATION: 30
  MAX_SCALE: 1.5
  MAX_TRANSLATE: 40
  MIN_SCALE: 0.75
  NUM_JOINTS: 17
  OUTPUT_SIZE: [128, 256]
  ROOT: data/coco
  SCALE_AWARE_SIGMA: False
  SCALE_TYPE: short
  SIGMA: 2
  TEST: val2017
  TRAIN: train2017
  WITH_CENTER: False
DATA_DIR:
DEBUG:
  DEBUG: True
  SAVE_BATCH_IMAGES_GT: False
  SAVE_BATCH_IMAGES_PRED: False
  SAVE_HEATMAPS_GT: True
  SAVE_HEATMAPS_PRED: True
  SAVE_TAGMAPS_PRED: True
DIST_BACKEND: nccl
FP16:
  DYNAMIC_LOSS_SCALE: True
  ENABLED: False
  STATIC_LOSS_SCALE: 1.0
GPUS: (0,)
LOG_DIR: log
LOSS:
  AE_LOSS_TYPE: exp
  HEATMAPS_LOSS_FACTOR: (1.0, 1.0)
  NUM_STAGES: 2
  PULL_LOSS_FACTOR: (0.001, 0.001)
  PUSH_LOSS_FACTOR: (0.001, 0.001)
  WITH_AE_LOSS: (True, False)
  WITH_HEATMAPS_LOSS: (True, True)
MODEL:
  EXTRA:
    DECONV:
      CAT_OUTPUT: [True]
      KERNEL_SIZE: [4]
      NUM_BASIC_BLOCKS: 4
      NUM_CHANNELS: [32]
      NUM_DECONVS: 1
    FINAL_CONV_KERNEL: 1
    PRETRAINED_LAYERS: ['*']
    STAGE2:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4, 4]
      NUM_BRANCHES: 2
      NUM_CHANNELS: [32, 64]
      NUM_MODULES: 1
    STAGE3:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4, 4, 4]
      NUM_BRANCHES: 3
      NUM_CHANNELS: [32, 64, 128]
      NUM_MODULES: 4
    STAGE4:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS: [4, 4, 4, 4]
      NUM_BRANCHES: 4
      NUM_CHANNELS: [32, 64, 128, 256]
      NUM_MODULES: 3
    STEM_INPLANES: 64
  INIT_WEIGHTS: True
  NAME: pose_higher_hrnet
  NUM_JOINTS: 17
  PRETRAINED: models/pytorch/imagenet/hrnet_w32-36af842e.pth
  SYNC_BN: False
  TAG_PER_JOINT: True
MULTIPROCESSING_DISTRIBUTED: False
OUTPUT_DIR: output
PIN_MEMORY: True
PRINT_FREQ: 100
RANK: 0
TEST:
  ADJUST: True
  DETECTION_THRESHOLD: 0.1
  FLIP_TEST: True
  IGNORE_CENTER: True
  IGNORE_TOO_MUCH: False
  IMAGES_PER_GPU: 1
  LOG_PROGRESS: False
  MODEL_FILE:
  NMS_KERNEL: 5
  NMS_PADDING: 2
  PROJECT2IMAGE: True
  REFINE: True
  SCALE_FACTOR: [1]
  TAG_THRESHOLD: 1.0
  USE_DETECTION_VAL: True
  WITH_AE: (True, False)
  WITH_HEATMAPS: (True, True)
TRAIN:
  BEGIN_EPOCH: 0
  CHECKPOINT:
  END_EPOCH: 300
  GAMMA1: 0.99
  GAMMA2: 0.0
  IMAGES_PER_GPU: 12
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP: [200, 260]
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: adam
  RESUME: False
  SHUFFLE: True
  WD: 0.0001
VERBOSE: True
WORKERS: 4
Use GPU: 0 for training
=> init weights from normal distribution
=> init weights from normal distribution
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init conv1.weight from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init conv1.weight from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init bn1.weight from models/pytorch/imagenet/hrnet_w32-36af842e.pth

**Comment by happydog555** [comment]
I specify one GPU.An error occurred.

**Comment by happydog555** [comment]
=> init stage4.2.fuse_layers.0.3.1.running_mean from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.running_var from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.running_var from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.num_batches_tracked from models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> init stage4.2.fuse_layers.0.3.1.num_batches_tracked from models/pytorch/imagenet/hrnet_w32-36af842e.pth
pytorch version is too old, how about build by yourself?
loading annotations into memory...
Done (t=21.08s)
creating index...
index created!
=> classes: ['__background__', 'person']
=> classes: ['__background__', 'person']
Dataset CocoKeypoints
    Number of datapoints: 64115
    Root Location: data/coco
    Transforms (if any): None
    Target Transforms (if any): None
Dataset CocoKeypoints
    Number of datapoints: 64115
    Root Location: data/coco
    Transforms (if any): None
    Target Transforms (if any): None
Traceback (most recent call last):
  File "tools/dist_train.py", line 319, in <module>
    main()
  File "tools/dist_train.py", line 123, in main
    tb_log_dir
  File "tools/dist_train.py", line 282, in main_worker
    final_output_dir, tb_log_dir, writer_dict, fp16=cfg.FP16.ENABLED)
  File "D:\UserData\LiMeng\POSE_ROOT\tools\..\lib\core\trainer.py", line 40, in do_train
    outputs = model(images).cuda()
  File "C:\Users\cust708\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\UserData\LiMeng\POSE_ROOT\tools\..\lib\models\pose_higher_hrnet.py", line 475, in forward
    x = self.conv1(x)
  File "C:\Users\cust708\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\cust708\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\cust708\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by Burceoneo12345** [comment]
I would like to know if this problem has been solved?

**Comment by anas-zafar** [comment]
@happydog555 were you able to solve the problem?
